import * as ExcelJS from "exceljs";
import { saveAs } from "file-saver";
import type { IpoRecord } from "../types/ipo";
import type { LedgerUser } from "../types/user";
import { createAuditLog } from "./auditService";
import pkg from "../../package.json";

type ReportScope = "current" | "all";

export type ReportFilters = {
  scope: ReportScope;
  portfolio: string;
  status: string;
  dateFrom: string;
  dateTo: string;
};

export type GeneratorMetadata = {
  user: LedgerUser;
  generatedAt: string;
};

const roundAmt = (val: number) => Math.round(val * 100) / 100;

const formatStatus = (status: string) => {
  if (!status) return "Unknown";
  return status.split("_").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
};

const formatDateForExcel = (dateString: string) => {
  if (!dateString) return "N/A";
  const d = new Date(dateString);
  if (isNaN(d.getTime())) return dateString;
  if (d.getFullYear() < 1900) return "N/A";
  return d;
};

const applyTableStyles = (
  sheet: ExcelJS.Worksheet, 
  title: string, 
  generatedAt: string, 
  generatedBy: string
) => {
  // Insert Header Rows
  sheet.spliceRows(1, 0, 
    [ "Portfolio Ledger" ],
    [ title ],
    [],
    [ `Generated On: ${generatedAt}` ],
    [ `Generated By: ${generatedBy}` ],
    []
  );

  sheet.getRow(1).font = { bold: true, size: 12, color: { argb: "FF555555" } };
  sheet.getRow(2).font = { bold: true, size: 16, color: { argb: "FF000000" } };
  sheet.getRow(4).font = { italic: true, color: { argb: "FF666666" } };
  sheet.getRow(5).font = { italic: true, color: { argb: "FF666666" } };

  const headerRowIndex = 7;
  const headerRow = sheet.getRow(headerRowIndex);
  headerRow.font = { bold: true };
  
  sheet.views = [{ state: "frozen", ySplit: headerRowIndex }];

  // Iterate over data rows for styling
  sheet.eachRow((row, rowNumber) => {
    if (rowNumber > headerRowIndex) {
      if (rowNumber % 2 === 0) {
        row.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "FFF9F9F9" }
        };
      }
    }
    
    if (rowNumber >= headerRowIndex) {
      row.alignment = { vertical: "middle" };
      row.eachCell((cell) => {
        cell.border = {
          top: { style: "thin", color: { argb: "FFDDDDDD" } },
          left: { style: "thin", color: { argb: "FFDDDDDD" } },
          bottom: { style: "thin", color: { argb: "FFDDDDDD" } },
          right: { style: "thin", color: { argb: "FFDDDDDD" } },
        };
      });
      row.height = 20;
    }
  });
};

const setupMetadataSheet = (
  workbook: ExcelJS.Workbook,
  metadata: GeneratorMetadata,
  filters: ReportFilters,
  reportName: string
) => {
  const sheet = workbook.addWorksheet("Metadata");
  
  sheet.columns = [
    { header: "Property", key: "prop", width: 25 },
    { header: "Value", key: "val", width: 45 },
  ];

  sheet.getRow(1).font = { bold: true };
  sheet.views = [{ state: "frozen", ySplit: 1 }];

  sheet.addRow({ prop: "Portfolio Ledger Version", val: pkg.version });
  sheet.addRow({ prop: "Report Type", val: reportName });
  sheet.addRow({ prop: "Generated By", val: metadata.user.name });
  sheet.addRow({ prop: "Generated On", val: metadata.generatedAt });
  
  const scopeStr = filters.scope === "all" ? "All Historical Data" : "Current Filtered Data";
  sheet.addRow({ prop: "Report Scope", val: scopeStr });

  const portStr = filters.portfolio === "all" ? "All Portfolios" : filters.portfolio === "portfolioAlpha" ? "Portfolio Alpha" : filters.portfolio === "portfolioBeta" ? "Portfolio Beta" : "All Portfolios";
  sheet.addRow({ prop: "Portfolio Filter", val: filters.scope === "all" ? "All Portfolios" : portStr });

  const statusStr = filters.status === "all" ? "All Statuses" : formatStatus(filters.status);
  sheet.addRow({ prop: "Status Filter", val: filters.scope === "all" ? "All Statuses" : statusStr });

  const dateStr = (filters.dateFrom || filters.dateTo) ? `${filters.dateFrom || "Start"} \u2192 ${filters.dateTo || "End"}` : "All Dates";
  sheet.addRow({ prop: "Date Range", val: filters.scope === "all" ? "All Dates" : dateStr });

  sheet.eachRow((row, rowNum) => {
    row.alignment = { vertical: "middle" };
    if (rowNum > 1) {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: "thin", color: { argb: "FFDDDDDD" } },
          left: { style: "thin", color: { argb: "FFDDDDDD" } },
          bottom: { style: "thin", color: { argb: "FFDDDDDD" } },
          right: { style: "thin", color: { argb: "FFDDDDDD" } },
        };
      });
      row.height = 20;
    }
  });
};

const saveWorkbookAndLog = async (
  workbook: ExcelJS.Workbook, 
  reportId: string, 
  reportName: string,
  dateStr: string,
  filters: ReportFilters,
  metadata: GeneratorMetadata
) => {
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
  saveAs(blob, `PortfolioLedger_${reportId}_${dateStr}.xlsx`);

  const portfolioFilterStr = filters.scope === "all" 
    ? "All Historical Data" 
    : filters.portfolio === "portfolioAlpha" ? "Portfolio Alpha" : filters.portfolio === "portfolioBeta" ? "Portfolio Beta" : "All Portfolios";
  const scopeStr = filters.scope === "all" ? "Unfiltered" : "Current Filtered Data";

  await createAuditLog({
    eventType: "report_exported",
    entityType: "report",
    entityId: reportId,
    userUid: metadata.user.uid,
    userName: metadata.user.name,
    description: `User exported ${reportName} (${portfolioFilterStr}, ${scopeStr})`,
    portfolioId: filters.scope === "current" && filters.portfolio !== "all" ? filters.portfolio : undefined,
  });
};

export const reportRegistry = {
  ipo_ledger: {
    name: "IPO Ledger",
    desc: "List of IPOs and their total P&L",
    generate: async (ipos: IpoRecord[], filters: ReportFilters, metadata: GeneratorMetadata, dateStr: string) => {
      const workbook = new ExcelJS.Workbook();
      const sheet = workbook.addWorksheet("IPO Ledger");

      sheet.columns = [
        { header: "IPO Name", key: "name", width: 30 },
        { header: "Portfolio", key: "portfolio", width: 20 },
        { header: "Listing Date", key: "date", width: 20 },
        { header: "Status", key: "status", width: 15 },
        { header: "Investment Amount", key: "investment", width: 25 },
        { header: "Listing Gain/Loss", key: "pnl", width: 25 },
        { header: "Final Settlement Amount", key: "finalCredit", width: 25 },
      ];

      ipos.forEach(ipo => {
        let invAmt = 0;
        let finalCredit = 0;
        Object.values(ipo.memberEntries || {}).forEach(m => {
          invAmt += (m.allottedAmount || 0);
          finalCredit += (m.finalBankCredit || 0);
        });

        sheet.addRow({
          name: ipo.ipoName,
          portfolio: ipo.portfolioName,
          date: formatDateForExcel(ipo.allotmentDate),
          status: formatStatus(ipo.status),
          investment: roundAmt(invAmt),
          pnl: roundAmt(ipo.calculationSnapshot.totalProfitLoss),
          finalCredit: roundAmt(finalCredit),
        });
      });

      sheet.getColumn("date").numFmt = "dd-mmm-yyyy";
      sheet.getColumn("investment").numFmt = "[$₹-en-IN]#,##0.00;[Red]-[$₹-en-IN]#,##0.00";
      sheet.getColumn("pnl").numFmt = "[$₹-en-IN]#,##0.00;[Red]-[$₹-en-IN]#,##0.00";
      sheet.getColumn("finalCredit").numFmt = "[$₹-en-IN]#,##0.00;[Red]-[$₹-en-IN]#,##0.00";

      applyTableStyles(sheet, "IPO Ledger", metadata.generatedAt, metadata.user.name);
      setupMetadataSheet(workbook, metadata, filters, "IPO Ledger");

      await saveWorkbookAndLog(workbook, "IPO_Ledger", "IPO Ledger", dateStr, filters, metadata);
    }
  },
  settlement_report: {
    name: "Settlement Report",
    desc: "All settlement instructions",
    generate: async (ipos: IpoRecord[], filters: ReportFilters, metadata: GeneratorMetadata, dateStr: string) => {
      const workbook = new ExcelJS.Workbook();
      const sheet = workbook.addWorksheet("Settlement Report");

      sheet.columns = [
        { header: "IPO Name", key: "ipoName", width: 25 },
        { header: "Listing Date", key: "date", width: 20 },
        { header: "From", key: "from", width: 20 },
        { header: "To", key: "to", width: 20 },
        { header: "Amount", key: "amount", width: 20 },
        { header: "Settlement Status", key: "status", width: 20 },
        { header: "Settlement Date", key: "settledAt", width: 20 },
        { header: "Days Pending", key: "daysPending", width: 15 },
      ];

      ipos.forEach(ipo => {
        const ipoDate = new Date(ipo.allotmentDate);
        const now = new Date();
        const daysDiff = !isNaN(ipoDate.getTime()) ? Math.floor((now.getTime() - ipoDate.getTime()) / (1000 * 3600 * 24)) : 0;

        ipo.calculationSnapshot.settlementInstructions.forEach(inst => {
          sheet.addRow({
            ipoName: ipo.ipoName,
            date: formatDateForExcel(ipo.allotmentDate),
            from: inst.from,
            to: inst.to,
            amount: roundAmt(inst.amount),
            status: formatStatus(inst.status),
            settledAt: inst.status === "settled" ? formatDateForExcel(inst.settledAt || "") : "N/A",
            daysPending: inst.status === "pending" ? Math.max(0, daysDiff) : "N/A",
          });
        });
      });

      sheet.getColumn("date").numFmt = "dd-mmm-yyyy";
      sheet.getColumn("settledAt").numFmt = "dd-mmm-yyyy";
      sheet.getColumn("amount").numFmt = "[$₹-en-IN]#,##0.00;[Red]-[$₹-en-IN]#,##0.00";

      applyTableStyles(sheet, "Settlement Report", metadata.generatedAt, metadata.user.name);
      setupMetadataSheet(workbook, metadata, filters, "Settlement Report");

      await saveWorkbookAndLog(workbook, "Settlement_Report", "Settlement Report", dateStr, filters, metadata);
    }
  },
  member_profit: {
    name: "Member Profit Report",
    desc: "Aggregated member performance and breakdown",
    generate: async (ipos: IpoRecord[], filters: ReportFilters, metadata: GeneratorMetadata, dateStr: string) => {
      const workbook = new ExcelJS.Workbook();

      const summarySheet = workbook.addWorksheet("Member Summary");
      const breakdownSheet = workbook.addWorksheet("Member Breakdown");
      
      // Breakdown Sheet Setup
      breakdownSheet.columns = [
        { header: "Member Name", key: "name", width: 25 },
        { header: "IPO Name", key: "ipoName", width: 25 },
        { header: "Portfolio", key: "portfolio", width: 20 },
        { header: "Listing Gain/Loss", key: "ipoPnl", width: 25 },
        { header: "Final Profit Allocation", key: "allocation", width: 25 },
        { header: "Listing Date", key: "date", width: 20 },
      ];

      // Aggregate for Summary while building Breakdown
      const memberTotals: Record<string, { memberName: string, totalProfit: number, ipoCount: number, portfolios: Set<string> }> = {};
      
      ipos.forEach(ipo => {
        ipo.calculationSnapshot.memberEntitlements.forEach(ent => {
          if (!memberTotals[ent.memberCode]) {
            memberTotals[ent.memberCode] = { memberName: ent.memberName, totalProfit: 0, ipoCount: 0, portfolios: new Set() };
          }
          
          if (ent.entitled !== 0 || ent.actual !== 0 || ent.net !== 0) {
             memberTotals[ent.memberCode].totalProfit += ent.entitled;
             memberTotals[ent.memberCode].ipoCount += 1;
             memberTotals[ent.memberCode].portfolios.add(ipo.portfolioName);

             breakdownSheet.addRow({
               name: ent.memberName,
               ipoName: ipo.ipoName,
               portfolio: ipo.portfolioName,
               ipoPnl: roundAmt(ipo.calculationSnapshot.totalProfitLoss),
               allocation: roundAmt(ent.entitled),
               date: formatDateForExcel(ipo.allotmentDate),
             });
          }
        });
      });

      breakdownSheet.getColumn("ipoPnl").numFmt = "[$₹-en-IN]#,##0.00;[Red]-[$₹-en-IN]#,##0.00";
      breakdownSheet.getColumn("allocation").numFmt = "[$₹-en-IN]#,##0.00;[Red]-[$₹-en-IN]#,##0.00";
      breakdownSheet.getColumn("date").numFmt = "dd-mmm-yyyy";

      // Summary Sheet Setup
      summarySheet.columns = [
        { header: "Member Name", key: "name", width: 25 },
        { header: "Total Profit", key: "total", width: 25 },
        { header: "Total IPOs Participated", key: "count", width: 25 },
        { header: "Portfolio Count", key: "portCount", width: 20 },
      ];

      Object.values(memberTotals).forEach(m => {
        summarySheet.addRow({
          name: m.memberName,
          total: roundAmt(m.totalProfit),
          count: m.ipoCount,
          portCount: m.portfolios.size,
        });
      });

      summarySheet.getColumn("total").numFmt = "[$₹-en-IN]#,##0.00;[Red]-[$₹-en-IN]#,##0.00";

      applyTableStyles(summarySheet, "Member Profit Report - Summary", metadata.generatedAt, metadata.user.name);
      applyTableStyles(breakdownSheet, "Member Profit Report - Breakdown", metadata.generatedAt, metadata.user.name);
      
      setupMetadataSheet(workbook, metadata, filters, "Member Profit Report");

      await saveWorkbookAndLog(workbook, "Member_Profit_Report", "Member Profit Report", dateStr, filters, metadata);
    }
  },
  portfolio_summary: {
    name: "Portfolio Summary",
    desc: "Aggregated stats per portfolio",
    generate: async (ipos: IpoRecord[], filters: ReportFilters, metadata: GeneratorMetadata, dateStr: string) => {
      const workbook = new ExcelJS.Workbook();
      const sheet = workbook.addWorksheet("Portfolio Summary");
      
      const portTotals: Record<string, { 
        name: string,
        count: number, 
        activeCount: number,
        settledCount: number,
        pendingCount: number,
        totalPnl: number,
        bestIpoName: string,
        bestIpoPnl: number,
        worstIpoName: string,
        worstIpoPnl: number
      }> = {};
      
      ipos.forEach(ipo => {
        const pid = ipo.portfolioId;
        if (!portTotals[pid]) {
          portTotals[pid] = { 
            name: ipo.portfolioName,
            count: 0, 
            activeCount: 0, 
            settledCount: 0,
            pendingCount: 0,
            totalPnl: 0,
            bestIpoName: "",
            bestIpoPnl: -Infinity,
            worstIpoName: "",
            worstIpoPnl: Infinity
          };
        }
        
        const stats = portTotals[pid];
        const pnl = ipo.calculationSnapshot.totalProfitLoss;

        stats.count += 1;
        stats.totalPnl += pnl;
        
        if (ipo.status === "active") stats.activeCount += 1;

        if (pnl > stats.bestIpoPnl) {
          stats.bestIpoPnl = pnl;
          stats.bestIpoName = ipo.ipoName;
        }
        if (pnl < stats.worstIpoPnl) {
          stats.worstIpoPnl = pnl;
          stats.worstIpoName = ipo.ipoName;
        }

        const instructions = ipo.calculationSnapshot.settlementInstructions || [];
        const hasPending = instructions.some(i => i.status === "pending" || !i.status);
        if (hasPending) {
          stats.pendingCount += 1;
        } else {
          stats.settledCount += 1;
        }
      });

      sheet.columns = [
        { header: "Portfolio Name", key: "name", width: 20 },
        { header: "Total IPOs", key: "count", width: 15 },
        { header: "Active IPOs", key: "active", width: 15 },
        { header: "Settled IPOs", key: "settled", width: 15 },
        { header: "Pending Settlements", key: "pending", width: 22 },
        { header: "Total P&L", key: "pnl", width: 25 },
        { header: "Average IPO P&L", key: "avgPnl", width: 25 },
        { header: "Best IPO", key: "bestIpo", width: 25 },
        { header: "Best IPO P&L", key: "bestPnl", width: 20 },
        { header: "Worst IPO", key: "worstIpo", width: 25 },
        { header: "Worst IPO P&L", key: "worstPnl", width: 20 },
      ];

      Object.values(portTotals).forEach((stats) => {
        sheet.addRow({
          name: stats.name,
          count: stats.count,
          active: stats.activeCount,
          settled: stats.settledCount,
          pending: stats.pendingCount,
          pnl: roundAmt(stats.totalPnl),
          avgPnl: stats.count > 0 ? roundAmt(stats.totalPnl / stats.count) : 0,
          bestIpo: stats.bestIpoName || "N/A",
          bestPnl: stats.bestIpoPnl !== -Infinity ? roundAmt(stats.bestIpoPnl) : 0,
          worstIpo: stats.worstIpoName || "N/A",
          worstPnl: stats.worstIpoPnl !== Infinity ? roundAmt(stats.worstIpoPnl) : 0,
        });
      });

      sheet.getColumn("pnl").numFmt = "[$₹-en-IN]#,##0.00;[Red]-[$₹-en-IN]#,##0.00";
      sheet.getColumn("avgPnl").numFmt = "[$₹-en-IN]#,##0.00;[Red]-[$₹-en-IN]#,##0.00";
      sheet.getColumn("bestPnl").numFmt = "[$₹-en-IN]#,##0.00;[Red]-[$₹-en-IN]#,##0.00";
      sheet.getColumn("worstPnl").numFmt = "[$₹-en-IN]#,##0.00;[Red]-[$₹-en-IN]#,##0.00";

      applyTableStyles(sheet, "Portfolio Summary", metadata.generatedAt, metadata.user.name);
      setupMetadataSheet(workbook, metadata, filters, "Portfolio Summary");

      await saveWorkbookAndLog(workbook, "Portfolio_Summary", "Portfolio Summary", dateStr, filters, metadata);
    }
  }
};
