import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const TermsConditionsPage = () => {
  return (
    <div className="min-h-screen bg-ledger-ink text-ledger-steel py-10 px-6">
      <div className="mx-auto max-w-4xl">
        <Link to="/login" className="flex items-center gap-2 text-sm text-[#8793a3] hover:text-white transition mb-8 w-fit">
          <ArrowLeft className="h-4 w-4" />
          Back to Login
        </Link>
        
        <div className="rounded border border-ledger-line bg-ledger-panel p-8 md:p-12">
          <p className="text-xs font-semibold uppercase tracking-widest text-[#8793a3] mb-2">Last Updated: June 2026 (v1.0)</p>
          <h1 className="text-3xl font-semibold text-white mb-8">Terms & Conditions</h1>
          
          <div className="space-y-8 text-sm leading-relaxed text-[#9aa6b5]">
            
            <section>
              <h2 className="text-lg font-medium text-white mb-3">1. Platform Nature</h2>
              <p>Portfolio Ledger (the "Platform") is strictly a portfolio tracking, record-keeping, reporting, analytics, and mathematical calculation utility. Users apply for IPOs entirely independently using their own personal PAN cards, Demat accounts, brokers, and funds. Portfolio Ledger strictly provides record-keeping, calculation, reporting, reconciliation, and analytics functionality. Portfolio Ledger does not pool funds, execute trades, manage investments, facilitate transfers, or operate collective investment arrangements.</p>
            </section>

            <section>
              <h2 className="text-lg font-medium text-white mb-3">2. Informational Use Only & No Financial Advice</h2>
              <p>The Platform is for informational use only. The Platform is not a registered investment adviser, broker, dealer, securities intermediary, portfolio manager, custodian, clearinghouse, payment processor, or financial institution. The Platform does not provide financial, legal, accounting, tax, or investment advice. You should consult with your own independent professional advisors before making any financial decisions.</p>
            </section>

            <section>
              <h2 className="text-lg font-medium text-white mb-3">3. User Data Responsibility</h2>
              <p>All records, ratios, and portfolio inputs are entirely user-supplied. You acknowledge and agree that you are solely responsible for the accuracy, completeness, and timeliness of all data entered into the Platform.</p>
            </section>

            <section>
              <h2 className="text-lg font-medium text-white mb-3">4. Calculation Disclaimer</h2>
              <p>All calculations, charts, AI analysis, and settlement summaries generated by the Platform are mathematical estimates based purely on user-provided inputs. Outputs may contain calculation errors, software bugs, or synchronization delays. Users are strictly responsible for independently verifying all mathematical calculations and outputs generated by the Platform before taking any real-world action.</p>
            </section>

            <section>
              <h2 className="text-lg font-medium text-white mb-3">5. No Reliance Clause</h2>
              <p>You expressly agree that you will not rely on the Platform's reports, calculations, analytics, suggested allocations, or settlement summaries for making financial, investment, or tax decisions. Any actions taken based on Platform outputs are done strictly at your own risk.</p>
            </section>

            <section>
              <h2 className="text-lg font-medium text-white mb-3">6. Limitation of Liability</h2>
              <p>To the maximum extent permitted by law, the operator(s) of Portfolio Ledger shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from your use of the Platform. This includes, but is not limited to, liability for investment losses, adverse tax consequences, data loss or corruption, calculation errors, or missed investment opportunities. Use of the platform is strictly at your own risk.</p>
            </section>

            <section>
              <h2 className="text-lg font-medium text-white mb-3">7. Service Availability & Data Accuracy Disclaimer</h2>
              <p>We do not guarantee that the service will be uninterrupted, secure, or error-free. Information is stored as submitted and is not independently verified by the Platform.</p>
            </section>

            <section>
              <h2 className="text-lg font-medium text-white mb-3">8. Indemnification</h2>
              <p>You agree to defend, indemnify, and hold harmless the operator(s) of the Platform from any and all claims, damages, obligations, losses, liabilities, costs, or debt arising from: (a) your use of the Platform; (b) any user disputes arising from incorrect data; (c) any regulatory investigations caused by your conduct; and (d) any third-party claims related to your data or personal investment activities.</p>
            </section>

            <section>
              <h2 className="text-lg font-medium text-white mb-3">9. Arbitration & Governing Law</h2>
              <p>Any dispute arising out of or relating to these Terms shall be resolved through binding arbitration. The venue for arbitration and governing law shall be determined by the Platform operators, and the proceedings shall be conducted on an individual basis, strictly prohibiting class actions.</p>
            </section>

            <section>
              <h2 className="text-lg font-medium text-white mb-3">10. Account Suspension & Termination</h2>
              <p>Platform administrators reserve the right to suspend or terminate your access to the Platform at any time, without prior notice, for any reason—including but not limited to violations of these Terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-medium text-white mb-3">11. Contact Information</h2>
              <p>For questions or legal concerns regarding these Terms, please contact your portfolio administrator.</p>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsConditionsPage;
